# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 20:58
from __future__ import unicode_literals

import apps.personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombres',
        ),
        migrations.AddField(
            model_name='persona',
            name='fnacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.personal.models.user_directory_path),
        ),
    ]
